"""Updated Album Model to include a cover column

Revision ID: 5401d8f9635a
Revises: b2b341169653
Create Date: 2024-11-07 14:34:25.158781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5401d8f9635a'
down_revision = 'b2b341169653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
